#!/bin/bash

# WLAN parameters
SSID="Docker"
HW_MODE="g"
CHANNEL="6"
PASSPHRASE="docker123"
WPA_MODE="WPA-PSK"

# Other parameters
SUBNET="192.168.0"
IP_AP="192.168.0.1"
NETMASK="/24"
DNS_SERVER="8.8.8.8"
DOCKER_NAME="ap-container"
CONF_FILE="hotspot-config.txt"
